### ISSUE TITLE
change "main searchable attribute" to "main attribute"

### ISSUE THREAD

**Issue by Haroenv** [algolia/create-instantsearch-app#32]
Clearer IMO

**Comment by francoischalifour** [comment]
We were discussing with @vvo if you could select the main attribute dynamically on the command-line like so:

1. Send a dummy search to the index
1. Retrieve the keys of the returned object
1. Propose a few attributes based on these keys (and bump up the ranking of keys like `name`, `title`, `description` because they are often used)

What do you think?

**Comment by Haroenv** [comment]
doing a search and getting the possible keys sounds great as a suggestion. Make sure it's still able to be dismissed easily though. I wouldn't go ahead and suggest one though, seems a bit over the top :)

**Comment by vvo** [comment]
As for feedback indeed when I first tried the tool, when reaching this question it was unclear:
- why am I being asked this so early, I just want to edit files
- where will this attribute be really used?

@sarahdayan also asked herself today what was the purpose of the attribute

I understand it is to prepopulate the hits widget with the right attribute so it looks good.

I would actually go for what we discussed together yes (what you proposed in your comment @francoischalifour, I think it would ease the process)
