### ISSUE TITLE
Add scheduled tests

### ISSUE THREAD

**Issue by tkrugg** [algolia/create-instantsearch-app#326]
## The problem

Since we don't lock dependencies our templates can stop working without us knowing.
I think the build is currently broken (I tried retriggring one on master branch and it failed)

## Solution

Schedule a daily build that runs the e2e tests

## Implementation

Travis cron job should be enough
https://docs.travis-ci.com/user/cron-jobs/

**Comment by francoischalifour** [comment]
I'm not sure I understand the problem.

We can detect if a dependency update breaks a template in a PR itself (sent by Renovate) because E2E tests are run there.

**Comment by francoischalifour** [comment]
I think having scheduled builds involve too much complexity and to be honest I don't understand what would be their added value?

Right now, we don't provide a lock file because the user could either use Yarn or npm (in case of a JavaScript template). However, we could generate cached lock files and delete the unwanted one at each Renovate upgrade (`package-lock.json.cached` for a Yarn project, `yarn.lock.cached` for an npm project).

What do you think?

**Comment by francoischalifour** [comment]
I honestly don't understand what problem having CRON jobs solves. What would be the flow? (job starts, install dependencies, copy `yarn.lock` to each template, commit, push, etc.)

Having manuel cached lock files would probably be easier to deal with.

**Comment by Haroenv** [comment]
CRON jobs are a switch to enable, cached lock files etc. take some work to implement
